# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Sistema Grafico Interativo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from ast import Lambda
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QWidget, QApplication
from PyQt5.QtCore import pyqtSignal
from OpenGL.GL import *
from OpenGL.GLUT import *
from OpenGL.GLU import *
from openglwidget import OpenGLWidget
from gla import GLWidget


class Ui_SGI(object):
    def setupUi(self, SGI):
        SGI.setObjectName("SGI")
        SGI.resize(921, 634)
        #SGI.setSizeGripEnabled(False)
        #SGI.setModal(False)

        #self.openGLWidget = OpenGLWidget(SGI)
        self.openGLWidget = GLWidget(SGI)
        

        #self.openGLWidget = QtWidgets.QOpenGLWidget(SGI)
        self.openGLWidget.setGeometry(QtCore.QRect(20, 20, 641, 551))
        self.openGLWidget.setObjectName("openGLWidget")
        
        self.tabWidget = QtWidgets.QTabWidget(SGI)
        self.tabWidget.setGeometry(QtCore.QRect(680, 20, 281, 551))
        self.tabWidget.setObjectName("tabWidget")
        self.tabObj = QtWidgets.QWidget()
        self.tabObj.setObjectName("tabObj")
        #---------------------------------------------Triângulo---------------------------------
        self.groupTriangulo = QtWidgets.QGroupBox(self.tabObj)
        self.groupTriangulo.setGeometry(QtCore.QRect(10, 160, 251, 151))
        self.groupTriangulo.setObjectName("groupTriangulo")

        self.label_2 = QtWidgets.QLabel(self.groupTriangulo)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 31, 21))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.groupTriangulo)
        self.label_4.setGeometry(QtCore.QRect(30, 80, 31, 21))
        self.label_4.setObjectName("label_4")
        self.xTriang1 = QtWidgets.QLineEdit(self.groupTriangulo)
        self.xTriang1.setGeometry(QtCore.QRect(70, 20, 31, 20))
        self.xTriang1.setObjectName("xTriang1")
        self.label_3 = QtWidgets.QLabel(self.groupTriangulo)
        self.label_3.setGeometry(QtCore.QRect(30, 50, 31, 21))
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.groupTriangulo)
        self.label_6.setGeometry(QtCore.QRect(50, 20, 31, 21))
        self.label_6.setObjectName("label_6")
        self.yTriang1 = QtWidgets.QLineEdit(self.groupTriangulo)
        self.yTriang1.setGeometry(QtCore.QRect(140, 20, 31, 20))
        self.yTriang1.setObjectName("yTriang1")
        self.label_8 = QtWidgets.QLabel(self.groupTriangulo)
        self.label_8.setGeometry(QtCore.QRect(120, 20, 31, 21))
        self.label_8.setObjectName("label_8")
        self.xTriang2 = QtWidgets.QLineEdit(self.groupTriangulo)
        self.xTriang2.setGeometry(QtCore.QRect(70, 50, 31, 20))
        self.xTriang2.setObjectName("xTriang2")
        self.yTriang2 = QtWidgets.QLineEdit(self.groupTriangulo)
        self.yTriang2.setGeometry(QtCore.QRect(140, 50, 31, 20))
        self.yTriang2.setObjectName("yTriang2")
        self.label_9 = QtWidgets.QLabel(self.groupTriangulo)
        self.label_9.setGeometry(QtCore.QRect(50, 50, 31, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupTriangulo)
        self.label_10.setGeometry(QtCore.QRect(120, 50, 31, 21))
        self.label_10.setObjectName("label_10")
        self.xTriang3 = QtWidgets.QLineEdit(self.groupTriangulo)
        self.xTriang3.setGeometry(QtCore.QRect(70, 80, 31, 20))
        self.xTriang3.setObjectName("xTriang3")
        self.yTriang3 = QtWidgets.QLineEdit(self.groupTriangulo)
        self.yTriang3.setGeometry(QtCore.QRect(140, 80, 31, 20))
        self.yTriang3.setObjectName("yTriang3")
        self.label_11 = QtWidgets.QLabel(self.groupTriangulo)
        self.label_11.setGeometry(QtCore.QRect(50, 80, 31, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupTriangulo)
        self.label_12.setGeometry(QtCore.QRect(120, 80, 31, 21))
        self.label_12.setObjectName("label_12")

        self.btTriangulo = QtWidgets.QPushButton(self.groupTriangulo)
        self.btTriangulo.setGeometry(QtCore.QRect(70, 120, 121, 23))
        self.btTriangulo.setObjectName("btTriangulo")

        #---------------------------------------------Ponto---------------------------------
        self.groupPonto = QtWidgets.QGroupBox(self.tabObj)
        self.groupPonto.setGeometry(QtCore.QRect(10, 20, 251, 121))
        self.groupPonto.setObjectName("groupPonto")
        self.label_5 = QtWidgets.QLabel(self.groupPonto)
        self.label_5.setGeometry(QtCore.QRect(30, 20, 31, 21))
        self.label_5.setObjectName("label_5")
        self.xPonto = QtWidgets.QLineEdit(self.groupPonto)
        self.xPonto.setGeometry(QtCore.QRect(50, 20, 31, 20))
        self.xPonto.setObjectName("xPonto")
        self.yPonto = QtWidgets.QLineEdit(self.groupPonto)
        self.yPonto.setGeometry(QtCore.QRect(50, 50, 31, 20))
        self.yPonto.setObjectName("yPonto")
        self.label_7 = QtWidgets.QLabel(self.groupPonto)
        self.label_7.setGeometry(QtCore.QRect(30, 50, 31, 21))
        self.label_7.setObjectName("label_7")

        self.btPonto = QtWidgets.QPushButton(self.groupPonto)
        self.btPonto.setGeometry(QtCore.QRect(70, 90, 121, 23))
        self.btPonto.setObjectName("btPonto")


        #---------------------------------------------Poli---------------------------------
        self.groupPoli = QtWidgets.QGroupBox(self.tabObj)
        self.groupPoli.setGeometry(QtCore.QRect(10, 320, 251, 191))
        self.groupPoli.setObjectName("groupPoli")

        self.label_13 = QtWidgets.QLabel(self.groupPoli)
        self.label_13.setGeometry(QtCore.QRect(30, 20, 31, 21))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupPoli)
        self.label_14.setGeometry(QtCore.QRect(30, 80, 31, 21))
        self.label_14.setObjectName("label_14")
        self.xPoli1 = QtWidgets.QLineEdit(self.groupPoli)
        self.xPoli1.setGeometry(QtCore.QRect(70, 20, 31, 20))
        self.xPoli1.setObjectName("xPoli1")
        self.label_15 = QtWidgets.QLabel(self.groupPoli)
        self.label_15.setGeometry(QtCore.QRect(30, 50, 31, 21))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupPoli)
        self.label_16.setGeometry(QtCore.QRect(50, 20, 31, 21))
        self.label_16.setObjectName("label_16")
        self.yPoli1 = QtWidgets.QLineEdit(self.groupPoli)
        self.yPoli1.setGeometry(QtCore.QRect(140, 20, 31, 20))
        self.yPoli1.setObjectName("yPoli1")
        self.label_17 = QtWidgets.QLabel(self.groupPoli)
        self.label_17.setGeometry(QtCore.QRect(120, 20, 31, 21))
        self.label_17.setObjectName("label_17")
        self.xPoli2 = QtWidgets.QLineEdit(self.groupPoli)
        self.xPoli2.setGeometry(QtCore.QRect(70, 50, 31, 20))
        self.xPoli2.setObjectName("xPoli2")
        self.yPoli2 = QtWidgets.QLineEdit(self.groupPoli)
        self.yPoli2.setGeometry(QtCore.QRect(140, 50, 31, 20))
        self.yPoli2.setObjectName("yPoli2")
        self.label_18 = QtWidgets.QLabel(self.groupPoli)
        self.label_18.setGeometry(QtCore.QRect(50, 50, 31, 21))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.groupPoli)
        self.label_19.setGeometry(QtCore.QRect(120, 50, 31, 21))
        self.label_19.setObjectName("label_19")
        self.xPoli3 = QtWidgets.QLineEdit(self.groupPoli)
        self.xPoli3.setGeometry(QtCore.QRect(70, 80, 31, 20))
        self.xPoli3.setObjectName("xPoli3")
        self.yPoli3 = QtWidgets.QLineEdit(self.groupPoli)
        self.yPoli3.setGeometry(QtCore.QRect(140, 80, 31, 20))
        self.yPoli3.setObjectName("yPoli3")
        self.label_20 = QtWidgets.QLabel(self.groupPoli)
        self.label_20.setGeometry(QtCore.QRect(50, 80, 31, 21))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.groupPoli)
        self.label_21.setGeometry(QtCore.QRect(120, 80, 31, 21))
        self.label_21.setObjectName("label_21")
        self.yPoli4 = QtWidgets.QLineEdit(self.groupPoli)
        self.yPoli4.setGeometry(QtCore.QRect(140, 110, 31, 20))
        self.yPoli4.setObjectName("yPoli4")
        self.xPoli4 = QtWidgets.QLineEdit(self.groupPoli)
        self.xPoli4.setGeometry(QtCore.QRect(70, 110, 31, 20))
        self.xPoli4.setObjectName("xPoli4")
        self.label_24 = QtWidgets.QLabel(self.groupPoli)
        self.label_24.setGeometry(QtCore.QRect(120, 110, 31, 21))
        self.label_24.setObjectName("label_24")
        self.label_22 = QtWidgets.QLabel(self.groupPoli)
        self.label_22.setGeometry(QtCore.QRect(50, 110, 31, 21))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.groupPoli)
        self.label_23.setGeometry(QtCore.QRect(30, 110, 31, 21))
        self.label_23.setObjectName("label_23")

        self.btPoli = QtWidgets.QPushButton(self.groupPoli)
        self.btPoli.setGeometry(QtCore.QRect(60, 160, 121, 23))
        self.btPoli.setObjectName("btPoli")

        #---------------------------------------------Reset---------------------------------

        self.btReset = QtWidgets.QPushButton(SGI)
        self.btReset.setGeometry(QtCore.QRect(20, 590, 121, 23))
        self.btReset.setObjectName("btReset")
        

        self.tabWidget.addTab(self.tabObj, "")
        self.tabCurva = QtWidgets.QWidget()
        self.tabCurva.setObjectName("tabCurva")
        self.tabWidget.addTab(self.tabCurva, "")


        self.retranslateUi(SGI)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SGI)


    def retranslateUi(self, SGI):
        _translate = QtCore.QCoreApplication.translate
        SGI.setWindowTitle(_translate("SGI", "Dialog"))
        self.groupTriangulo.setTitle(_translate("SGI", "Insira os pontos do triâgulo:"))
        self.label_2.setText(_translate("SGI", "1:"))
        self.label_4.setText(_translate("SGI", "3:"))
        self.label_3.setText(_translate("SGI", "2:"))
        self.btTriangulo.setText(_translate("SGI", "Desenhar Triângulo"))
        self.label_6.setText(_translate("SGI", "X:"))
        self.label_8.setText(_translate("SGI", "Y:"))
        self.label_9.setText(_translate("SGI", "X:"))
        self.label_10.setText(_translate("SGI", "Y:"))
        self.label_11.setText(_translate("SGI", "X:"))
        self.label_12.setText(_translate("SGI", "Y:"))
        self.groupPonto.setTitle(_translate("SGI", "Insira os coordenadas do ponto:"))
        self.label_5.setText(_translate("SGI", "X:"))
        self.label_7.setText(_translate("SGI", "Y:"))
        self.btPonto.setText(_translate("SGI", "Desenhar Ponto"))
        self.groupPoli.setTitle(_translate("SGI", "Insira os pontos do triâgulo:"))
        self.label_13.setText(_translate("SGI", "1:"))
        self.label_14.setText(_translate("SGI", "3:"))
        self.label_15.setText(_translate("SGI", "2:"))
        self.btPoli.setText(_translate("SGI", "Desenhar Polígono"))
        self.label_16.setText(_translate("SGI", "X:"))
        self.label_17.setText(_translate("SGI", "Y:"))
        self.label_18.setText(_translate("SGI", "X:"))
        self.label_19.setText(_translate("SGI", "Y:"))
        self.label_20.setText(_translate("SGI", "X:"))
        self.label_21.setText(_translate("SGI", "Y:"))
        self.label_24.setText(_translate("SGI", "Y:"))
        self.label_22.setText(_translate("SGI", "X:"))
        self.label_23.setText(_translate("SGI", "4:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabObj), _translate("SGI", "Objetos"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCurva), _translate("SGI", "Curva"))
        self.btReset.setText(_translate("SGI", "Resetar"))

            

#if __name__ == "__main__":
#    import sys
#    app = QtWidgets.QApplication(sys.argv)
#    SGI = QtWidgets.QDialog()
#    ui = Ui_SGI()
#    ui.setupUi(SGI)
#    SGI.show()
#    sys.exit(app.exec_())